//
// Created by Mika Auer on 09.05.20.
//

#ifndef SATELLITE_ENCODER_CPP_CONSTANTS_H
#define SATELLITE_ENCODER_CPP_CONSTANTS_H

#define CODE_SIZE 1023
#define NUMBER_OF_REGISTERS 10
#define NUMBER_OF_SATELLITES 4

#endif //SATELLITE_ENCODER_CPP_CONSTANTS_H
